stages:
  - mirror

mirror_to_github:
  stage: mirror
  image: alpine:3.20
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  before_script:
    - apk add --no-cache git ca-certificates
    - git config --global user.email "ci-mirror@flowboard.local"
    - git config --global user.name "GitLab Mirror Bot"
  script:
    - git remote remove github 2>/dev/null || true
    - git remote add github https://Selimo100:${GITHUB_TOKEN}@github.com/Selimo100/FlowBoard.git
    - git push github HEAD:main
